services:
  web:
    container_name: trump-towers-pune-frontend

    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_PATH: ${NEXT_PUBLIC_PATH}
        BASEPATH_PREFIX: ${BASEPATH_PREFIX}
        ASSET_PREFIX: ${ASSET_PREFIX}
        API_DOMAIN_NAME: ${API_DOMAIN_NAME}
        FRONTEND_TOKEN_KEY: ${FRONTEND_TOKEN_KEY}

    env_file:
      - .env

    volumes:
      - ./public:/app/public

    environment:
      NODE_ENV: production
      PORT: 2986
      HOSTNAME: "0.0.0.0"

    ports:
      - "2986:2986"

    command: node server.js
    restart: unless-stopped